//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoLoginDTO", Namespace="http://schemas.datacontract.org/2004/07/uy.edu.ort.taller.aplicaciones.dominio.DT" +
        "O")]
    public partial class ResultadoLoginDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool LoginOkField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LoginOk {
            get {
                return this.LoginOkField;
            }
            set {
                if ((this.LoginOkField.Equals(value) != true)) {
                    this.LoginOkField = value;
                    this.RaisePropertyChanged("LoginOk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidoDTO", Namespace="http://schemas.datacontract.org/2004/07/uy.edu.ort.taller.aplicaciones.dominio.DT" +
        "O")]
    public partial class PedidoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool AprobadoField;
        
        private string DescripcionField;
        
        private string EjecutivoField;
        
        private System.DateTime FechaField;
        
        private int PedidoIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aprobado {
            get {
                return this.AprobadoField;
            }
            set {
                if ((this.AprobadoField.Equals(value) != true)) {
                    this.AprobadoField = value;
                    this.RaisePropertyChanged("Aprobado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ejecutivo {
            get {
                return this.EjecutivoField;
            }
            set {
                if ((object.ReferenceEquals(this.EjecutivoField, value) != true)) {
                    this.EjecutivoField = value;
                    this.RaisePropertyChanged("Ejecutivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PedidoId {
            get {
                return this.PedidoIdField;
            }
            set {
                if ((this.PedidoIdField.Equals(value) != true)) {
                    this.PedidoIdField = value;
                    this.RaisePropertyChanged("PedidoId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoDTO", Namespace="http://schemas.datacontract.org/2004/07/uy.edu.ort.taller.aplicaciones.dominio.DT" +
        "O")]
    public partial class ProductoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private string NombreField;
        
        private int ProductoIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductoId {
            get {
                return this.ProductoIdField;
            }
            set {
                if ((this.ProductoIdField.Equals(value) != true)) {
                    this.ProductoIdField = value;
                    this.RaisePropertyChanged("ProductoId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValorAtributoDTO", Namespace="http://schemas.datacontract.org/2004/07/uy.edu.ort.taller.aplicaciones.dominio.DT" +
        "O")]
    public partial class ValorAtributoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NombreField;
        
        private System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ValorDTO> ValoresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ValorDTO> Valores {
            get {
                return this.ValoresField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoresField, value) != true)) {
                    this.ValoresField = value;
                    this.RaisePropertyChanged("Valores");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValorDTO", Namespace="http://schemas.datacontract.org/2004/07/uy.edu.ort.taller.aplicaciones.dominio.DT" +
        "O")]
    public partial class ValorDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ValorStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorString {
            get {
                return this.ValorStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorStringField, value) != true)) {
                    this.ValorStringField = value;
                    this.RaisePropertyChanged("ValorString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivoDTO", Namespace="http://schemas.datacontract.org/2004/07/uy.edu.ort.taller.aplicaciones.dominio.DT" +
        "O")]
    public partial class ArchivoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ArchivoIdField;
        
        private string NombreField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArchivoId {
            get {
                return this.ArchivoIdField;
            }
            set {
                if ((this.ArchivoIdField.Equals(value) != true)) {
                    this.ArchivoIdField = value;
                    this.RaisePropertyChanged("ArchivoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CantidadProductoPedidoDTO", Namespace="http://schemas.datacontract.org/2004/07/uy.edu.ort.taller.aplicaciones.dominio.DT" +
        "O")]
    public partial class CantidadProductoPedidoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CantidadPedidaField;
        
        private string ProductoCodigoField;
        
        private int ProductoIdField;
        
        private string ProductoNombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadPedida {
            get {
                return this.CantidadPedidaField;
            }
            set {
                if ((this.CantidadPedidaField.Equals(value) != true)) {
                    this.CantidadPedidaField = value;
                    this.RaisePropertyChanged("CantidadPedida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductoCodigo {
            get {
                return this.ProductoCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoCodigoField, value) != true)) {
                    this.ProductoCodigoField = value;
                    this.RaisePropertyChanged("ProductoCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductoId {
            get {
                return this.ProductoIdField;
            }
            set {
                if ((this.ProductoIdField.Equals(value) != true)) {
                    this.ProductoIdField = value;
                    this.RaisePropertyChanged("ProductoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductoNombre {
            get {
                return this.ProductoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoNombreField, value) != true)) {
                    this.ProductoNombreField = value;
                    this.RaisePropertyChanged("ProductoNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ApiDistribuidores.ApiDistribuidores")]
    public interface ApiDistribuidores {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApiDistribuidores/Login", ReplyAction="urn:ApiDistribuidores/LoginResponse")]
        System.IAsyncResult BeginLogin(string login, string password, System.AsyncCallback callback, object asyncState);
        
        uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ResultadoLoginDTO EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApiDistribuidores/ListarPedidosDistribuidor", ReplyAction="urn:ApiDistribuidores/ListarPedidosDistribuidorResponse")]
        System.IAsyncResult BeginListarPedidosDistribuidor(string loginDistribuidor, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.PedidoDTO> EndListarPedidosDistribuidor(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApiDistribuidores/CambiarEstadoPedido", ReplyAction="urn:ApiDistribuidores/CambiarEstadoPedidoResponse")]
        System.IAsyncResult BeginCambiarEstadoPedido(int idPedido, bool nuevoEstado, System.AsyncCallback callback, object asyncState);
        
        bool EndCambiarEstadoPedido(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApiDistribuidores/ListarProductos", ReplyAction="urn:ApiDistribuidores/ListarProductosResponse")]
        System.IAsyncResult BeginListarProductos(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ProductoDTO> EndListarProductos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApiDistribuidores/ListarAtributosProducto", ReplyAction="urn:ApiDistribuidores/ListarAtributosProductoResponse")]
        System.IAsyncResult BeginListarAtributosProducto(int idProducto, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ValorAtributoDTO> EndListarAtributosProducto(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApiDistribuidores/ListarImagenesProducto", ReplyAction="urn:ApiDistribuidores/ListarImagenesProductoResponse")]
        System.IAsyncResult BeginListarImagenesProducto(int idProducto, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO> EndListarImagenesProducto(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApiDistribuidores/ListarVideosProducto", ReplyAction="urn:ApiDistribuidores/ListarVideosProductoResponse")]
        System.IAsyncResult BeginListarVideosProducto(int idProducto, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO> EndListarVideosProducto(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApiDistribuidores/ListarProductosPedido", ReplyAction="urn:ApiDistribuidores/ListarProductosPedidoResponse")]
        System.IAsyncResult BeginListarProductosPedido(int idPedido, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.CantidadProductoPedidoDTO> EndListarProductosPedido(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApiDistribuidoresChannel : uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ResultadoLoginDTO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ResultadoLoginDTO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarPedidosDistribuidorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListarPedidosDistribuidorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.PedidoDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.PedidoDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CambiarEstadoPedidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CambiarEstadoPedidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarProductosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListarProductosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ProductoDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ProductoDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarAtributosProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListarAtributosProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ValorAtributoDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ValorAtributoDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarImagenesProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListarImagenesProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarVideosProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListarVideosProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarProductosPedidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListarProductosPedidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.CantidadProductoPedidoDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.CantidadProductoPedidoDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiDistribuidoresClient : System.ServiceModel.ClientBase<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores>, uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores {
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginListarPedidosDistribuidorDelegate;
        
        private EndOperationDelegate onEndListarPedidosDistribuidorDelegate;
        
        private System.Threading.SendOrPostCallback onListarPedidosDistribuidorCompletedDelegate;
        
        private BeginOperationDelegate onBeginCambiarEstadoPedidoDelegate;
        
        private EndOperationDelegate onEndCambiarEstadoPedidoDelegate;
        
        private System.Threading.SendOrPostCallback onCambiarEstadoPedidoCompletedDelegate;
        
        private BeginOperationDelegate onBeginListarProductosDelegate;
        
        private EndOperationDelegate onEndListarProductosDelegate;
        
        private System.Threading.SendOrPostCallback onListarProductosCompletedDelegate;
        
        private BeginOperationDelegate onBeginListarAtributosProductoDelegate;
        
        private EndOperationDelegate onEndListarAtributosProductoDelegate;
        
        private System.Threading.SendOrPostCallback onListarAtributosProductoCompletedDelegate;
        
        private BeginOperationDelegate onBeginListarImagenesProductoDelegate;
        
        private EndOperationDelegate onEndListarImagenesProductoDelegate;
        
        private System.Threading.SendOrPostCallback onListarImagenesProductoCompletedDelegate;
        
        private BeginOperationDelegate onBeginListarVideosProductoDelegate;
        
        private EndOperationDelegate onEndListarVideosProductoDelegate;
        
        private System.Threading.SendOrPostCallback onListarVideosProductoCompletedDelegate;
        
        private BeginOperationDelegate onBeginListarProductosPedidoDelegate;
        
        private EndOperationDelegate onEndListarProductosPedidoDelegate;
        
        private System.Threading.SendOrPostCallback onListarProductosPedidoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ApiDistribuidoresClient() {
        }
        
        public ApiDistribuidoresClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiDistribuidoresClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiDistribuidoresClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiDistribuidoresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<ListarPedidosDistribuidorCompletedEventArgs> ListarPedidosDistribuidorCompleted;
        
        public event System.EventHandler<CambiarEstadoPedidoCompletedEventArgs> CambiarEstadoPedidoCompleted;
        
        public event System.EventHandler<ListarProductosCompletedEventArgs> ListarProductosCompleted;
        
        public event System.EventHandler<ListarAtributosProductoCompletedEventArgs> ListarAtributosProductoCompleted;
        
        public event System.EventHandler<ListarImagenesProductoCompletedEventArgs> ListarImagenesProductoCompleted;
        
        public event System.EventHandler<ListarVideosProductoCompletedEventArgs> ListarVideosProductoCompleted;
        
        public event System.EventHandler<ListarProductosPedidoCompletedEventArgs> ListarProductosPedidoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.BeginLogin(string login, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(login, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ResultadoLoginDTO uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).BeginLogin(login, password, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ResultadoLoginDTO retVal = ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string login, string password) {
            this.LoginAsync(login, password, null);
        }
        
        public void LoginAsync(string login, string password, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        login,
                        password}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.BeginListarPedidosDistribuidor(string loginDistribuidor, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListarPedidosDistribuidor(loginDistribuidor, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.PedidoDTO> uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.EndListarPedidosDistribuidor(System.IAsyncResult result) {
            return base.Channel.EndListarPedidosDistribuidor(result);
        }
        
        private System.IAsyncResult OnBeginListarPedidosDistribuidor(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string loginDistribuidor = ((string)(inValues[0]));
            return ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).BeginListarPedidosDistribuidor(loginDistribuidor, callback, asyncState);
        }
        
        private object[] OnEndListarPedidosDistribuidor(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.PedidoDTO> retVal = ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).EndListarPedidosDistribuidor(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListarPedidosDistribuidorCompleted(object state) {
            if ((this.ListarPedidosDistribuidorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListarPedidosDistribuidorCompleted(this, new ListarPedidosDistribuidorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListarPedidosDistribuidorAsync(string loginDistribuidor) {
            this.ListarPedidosDistribuidorAsync(loginDistribuidor, null);
        }
        
        public void ListarPedidosDistribuidorAsync(string loginDistribuidor, object userState) {
            if ((this.onBeginListarPedidosDistribuidorDelegate == null)) {
                this.onBeginListarPedidosDistribuidorDelegate = new BeginOperationDelegate(this.OnBeginListarPedidosDistribuidor);
            }
            if ((this.onEndListarPedidosDistribuidorDelegate == null)) {
                this.onEndListarPedidosDistribuidorDelegate = new EndOperationDelegate(this.OnEndListarPedidosDistribuidor);
            }
            if ((this.onListarPedidosDistribuidorCompletedDelegate == null)) {
                this.onListarPedidosDistribuidorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListarPedidosDistribuidorCompleted);
            }
            base.InvokeAsync(this.onBeginListarPedidosDistribuidorDelegate, new object[] {
                        loginDistribuidor}, this.onEndListarPedidosDistribuidorDelegate, this.onListarPedidosDistribuidorCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.BeginCambiarEstadoPedido(int idPedido, bool nuevoEstado, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCambiarEstadoPedido(idPedido, nuevoEstado, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.EndCambiarEstadoPedido(System.IAsyncResult result) {
            return base.Channel.EndCambiarEstadoPedido(result);
        }
        
        private System.IAsyncResult OnBeginCambiarEstadoPedido(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idPedido = ((int)(inValues[0]));
            bool nuevoEstado = ((bool)(inValues[1]));
            return ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).BeginCambiarEstadoPedido(idPedido, nuevoEstado, callback, asyncState);
        }
        
        private object[] OnEndCambiarEstadoPedido(System.IAsyncResult result) {
            bool retVal = ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).EndCambiarEstadoPedido(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCambiarEstadoPedidoCompleted(object state) {
            if ((this.CambiarEstadoPedidoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CambiarEstadoPedidoCompleted(this, new CambiarEstadoPedidoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CambiarEstadoPedidoAsync(int idPedido, bool nuevoEstado) {
            this.CambiarEstadoPedidoAsync(idPedido, nuevoEstado, null);
        }
        
        public void CambiarEstadoPedidoAsync(int idPedido, bool nuevoEstado, object userState) {
            if ((this.onBeginCambiarEstadoPedidoDelegate == null)) {
                this.onBeginCambiarEstadoPedidoDelegate = new BeginOperationDelegate(this.OnBeginCambiarEstadoPedido);
            }
            if ((this.onEndCambiarEstadoPedidoDelegate == null)) {
                this.onEndCambiarEstadoPedidoDelegate = new EndOperationDelegate(this.OnEndCambiarEstadoPedido);
            }
            if ((this.onCambiarEstadoPedidoCompletedDelegate == null)) {
                this.onCambiarEstadoPedidoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCambiarEstadoPedidoCompleted);
            }
            base.InvokeAsync(this.onBeginCambiarEstadoPedidoDelegate, new object[] {
                        idPedido,
                        nuevoEstado}, this.onEndCambiarEstadoPedidoDelegate, this.onCambiarEstadoPedidoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.BeginListarProductos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListarProductos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ProductoDTO> uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.EndListarProductos(System.IAsyncResult result) {
            return base.Channel.EndListarProductos(result);
        }
        
        private System.IAsyncResult OnBeginListarProductos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).BeginListarProductos(callback, asyncState);
        }
        
        private object[] OnEndListarProductos(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ProductoDTO> retVal = ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).EndListarProductos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListarProductosCompleted(object state) {
            if ((this.ListarProductosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListarProductosCompleted(this, new ListarProductosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListarProductosAsync() {
            this.ListarProductosAsync(null);
        }
        
        public void ListarProductosAsync(object userState) {
            if ((this.onBeginListarProductosDelegate == null)) {
                this.onBeginListarProductosDelegate = new BeginOperationDelegate(this.OnBeginListarProductos);
            }
            if ((this.onEndListarProductosDelegate == null)) {
                this.onEndListarProductosDelegate = new EndOperationDelegate(this.OnEndListarProductos);
            }
            if ((this.onListarProductosCompletedDelegate == null)) {
                this.onListarProductosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListarProductosCompleted);
            }
            base.InvokeAsync(this.onBeginListarProductosDelegate, null, this.onEndListarProductosDelegate, this.onListarProductosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.BeginListarAtributosProducto(int idProducto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListarAtributosProducto(idProducto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ValorAtributoDTO> uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.EndListarAtributosProducto(System.IAsyncResult result) {
            return base.Channel.EndListarAtributosProducto(result);
        }
        
        private System.IAsyncResult OnBeginListarAtributosProducto(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idProducto = ((int)(inValues[0]));
            return ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).BeginListarAtributosProducto(idProducto, callback, asyncState);
        }
        
        private object[] OnEndListarAtributosProducto(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ValorAtributoDTO> retVal = ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).EndListarAtributosProducto(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListarAtributosProductoCompleted(object state) {
            if ((this.ListarAtributosProductoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListarAtributosProductoCompleted(this, new ListarAtributosProductoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListarAtributosProductoAsync(int idProducto) {
            this.ListarAtributosProductoAsync(idProducto, null);
        }
        
        public void ListarAtributosProductoAsync(int idProducto, object userState) {
            if ((this.onBeginListarAtributosProductoDelegate == null)) {
                this.onBeginListarAtributosProductoDelegate = new BeginOperationDelegate(this.OnBeginListarAtributosProducto);
            }
            if ((this.onEndListarAtributosProductoDelegate == null)) {
                this.onEndListarAtributosProductoDelegate = new EndOperationDelegate(this.OnEndListarAtributosProducto);
            }
            if ((this.onListarAtributosProductoCompletedDelegate == null)) {
                this.onListarAtributosProductoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListarAtributosProductoCompleted);
            }
            base.InvokeAsync(this.onBeginListarAtributosProductoDelegate, new object[] {
                        idProducto}, this.onEndListarAtributosProductoDelegate, this.onListarAtributosProductoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.BeginListarImagenesProducto(int idProducto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListarImagenesProducto(idProducto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO> uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.EndListarImagenesProducto(System.IAsyncResult result) {
            return base.Channel.EndListarImagenesProducto(result);
        }
        
        private System.IAsyncResult OnBeginListarImagenesProducto(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idProducto = ((int)(inValues[0]));
            return ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).BeginListarImagenesProducto(idProducto, callback, asyncState);
        }
        
        private object[] OnEndListarImagenesProducto(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO> retVal = ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).EndListarImagenesProducto(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListarImagenesProductoCompleted(object state) {
            if ((this.ListarImagenesProductoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListarImagenesProductoCompleted(this, new ListarImagenesProductoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListarImagenesProductoAsync(int idProducto) {
            this.ListarImagenesProductoAsync(idProducto, null);
        }
        
        public void ListarImagenesProductoAsync(int idProducto, object userState) {
            if ((this.onBeginListarImagenesProductoDelegate == null)) {
                this.onBeginListarImagenesProductoDelegate = new BeginOperationDelegate(this.OnBeginListarImagenesProducto);
            }
            if ((this.onEndListarImagenesProductoDelegate == null)) {
                this.onEndListarImagenesProductoDelegate = new EndOperationDelegate(this.OnEndListarImagenesProducto);
            }
            if ((this.onListarImagenesProductoCompletedDelegate == null)) {
                this.onListarImagenesProductoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListarImagenesProductoCompleted);
            }
            base.InvokeAsync(this.onBeginListarImagenesProductoDelegate, new object[] {
                        idProducto}, this.onEndListarImagenesProductoDelegate, this.onListarImagenesProductoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.BeginListarVideosProducto(int idProducto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListarVideosProducto(idProducto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO> uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.EndListarVideosProducto(System.IAsyncResult result) {
            return base.Channel.EndListarVideosProducto(result);
        }
        
        private System.IAsyncResult OnBeginListarVideosProducto(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idProducto = ((int)(inValues[0]));
            return ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).BeginListarVideosProducto(idProducto, callback, asyncState);
        }
        
        private object[] OnEndListarVideosProducto(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO> retVal = ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).EndListarVideosProducto(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListarVideosProductoCompleted(object state) {
            if ((this.ListarVideosProductoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListarVideosProductoCompleted(this, new ListarVideosProductoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListarVideosProductoAsync(int idProducto) {
            this.ListarVideosProductoAsync(idProducto, null);
        }
        
        public void ListarVideosProductoAsync(int idProducto, object userState) {
            if ((this.onBeginListarVideosProductoDelegate == null)) {
                this.onBeginListarVideosProductoDelegate = new BeginOperationDelegate(this.OnBeginListarVideosProducto);
            }
            if ((this.onEndListarVideosProductoDelegate == null)) {
                this.onEndListarVideosProductoDelegate = new EndOperationDelegate(this.OnEndListarVideosProducto);
            }
            if ((this.onListarVideosProductoCompletedDelegate == null)) {
                this.onListarVideosProductoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListarVideosProductoCompleted);
            }
            base.InvokeAsync(this.onBeginListarVideosProductoDelegate, new object[] {
                        idProducto}, this.onEndListarVideosProductoDelegate, this.onListarVideosProductoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.BeginListarProductosPedido(int idPedido, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListarProductosPedido(idPedido, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.CantidadProductoPedidoDTO> uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores.EndListarProductosPedido(System.IAsyncResult result) {
            return base.Channel.EndListarProductosPedido(result);
        }
        
        private System.IAsyncResult OnBeginListarProductosPedido(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idPedido = ((int)(inValues[0]));
            return ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).BeginListarProductosPedido(idPedido, callback, asyncState);
        }
        
        private object[] OnEndListarProductosPedido(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.CantidadProductoPedidoDTO> retVal = ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores)(this)).EndListarProductosPedido(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListarProductosPedidoCompleted(object state) {
            if ((this.ListarProductosPedidoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListarProductosPedidoCompleted(this, new ListarProductosPedidoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListarProductosPedidoAsync(int idPedido) {
            this.ListarProductosPedidoAsync(idPedido, null);
        }
        
        public void ListarProductosPedidoAsync(int idPedido, object userState) {
            if ((this.onBeginListarProductosPedidoDelegate == null)) {
                this.onBeginListarProductosPedidoDelegate = new BeginOperationDelegate(this.OnBeginListarProductosPedido);
            }
            if ((this.onEndListarProductosPedidoDelegate == null)) {
                this.onEndListarProductosPedidoDelegate = new EndOperationDelegate(this.OnEndListarProductosPedido);
            }
            if ((this.onListarProductosPedidoCompletedDelegate == null)) {
                this.onListarProductosPedidoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListarProductosPedidoCompleted);
            }
            base.InvokeAsync(this.onBeginListarProductosPedidoDelegate, new object[] {
                        idPedido}, this.onEndListarProductosPedidoDelegate, this.onListarProductosPedidoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores CreateChannel() {
            return new ApiDistribuidoresClientChannel(this);
        }
        
        private class ApiDistribuidoresClientChannel : ChannelBase<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores>, uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores {
            
            public ApiDistribuidoresClientChannel(System.ServiceModel.ClientBase<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ApiDistribuidores> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLogin(string login, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = login;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ResultadoLoginDTO EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ResultadoLoginDTO _result = ((uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ResultadoLoginDTO)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListarPedidosDistribuidor(string loginDistribuidor, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = loginDistribuidor;
                System.IAsyncResult _result = base.BeginInvoke("ListarPedidosDistribuidor", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.PedidoDTO> EndListarPedidosDistribuidor(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.PedidoDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.PedidoDTO>)(base.EndInvoke("ListarPedidosDistribuidor", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCambiarEstadoPedido(int idPedido, bool nuevoEstado, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = idPedido;
                _args[1] = nuevoEstado;
                System.IAsyncResult _result = base.BeginInvoke("CambiarEstadoPedido", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndCambiarEstadoPedido(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("CambiarEstadoPedido", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListarProductos(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ListarProductos", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ProductoDTO> EndListarProductos(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ProductoDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ProductoDTO>)(base.EndInvoke("ListarProductos", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListarAtributosProducto(int idProducto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = idProducto;
                System.IAsyncResult _result = base.BeginInvoke("ListarAtributosProducto", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ValorAtributoDTO> EndListarAtributosProducto(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ValorAtributoDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ValorAtributoDTO>)(base.EndInvoke("ListarAtributosProducto", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListarImagenesProducto(int idProducto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = idProducto;
                System.IAsyncResult _result = base.BeginInvoke("ListarImagenesProducto", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO> EndListarImagenesProducto(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO>)(base.EndInvoke("ListarImagenesProducto", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListarVideosProducto(int idProducto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = idProducto;
                System.IAsyncResult _result = base.BeginInvoke("ListarVideosProducto", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO> EndListarVideosProducto(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.ArchivoDTO>)(base.EndInvoke("ListarVideosProducto", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListarProductosPedido(int idPedido, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = idPedido;
                System.IAsyncResult _result = base.BeginInvoke("ListarProductosPedido", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.CantidadProductoPedidoDTO> EndListarProductosPedido(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.CantidadProductoPedidoDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<uy.edu.ort.taller.aplicaciones.clientedistribuidores.ApiDistribuidores.CantidadProductoPedidoDTO>)(base.EndInvoke("ListarProductosPedido", _args, result)));
                return _result;
            }
        }
    }
}
